import type { CitizenReport } from "@/lib/types";

/** Demo citizen reports seeded at real Bengaluru road coordinates.
 *  Photos use Google Street View Static API at the exact lat/lng — real street-level imagery. */

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}

function streetView(lat: number, lng: number, heading: number, pitch = 10): string {
  const key = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY ?? "";
  return `https://maps.googleapis.com/maps/api/streetview?size=800x600&location=${lat},${lng}&heading=${heading}&fov=90&pitch=${pitch}&key=${key}`;
}

export const DEMO_REPORTS: CitizenReport[] = [
  {
    id: "demo-1",
    createdAt: hoursAgo(0.3),
    violationType: "double_parking",
    note: "Blocking entire lane, cars stuck for 10+ minutes",
    lat: 12.9758,
    lng: 77.6096,
    accuracyM: 8,
    photoUrl: streetView(12.9758, 77.6096, 90),
    snappedRoadId: "mg-road-metro",
    snappedRoadName: "MG Road",
    snappedZone: "Central",
    snappedDistanceM: 18,
    reporterMasked: "+91 ●●●●● ●342",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.91,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-2",
    createdAt: hoursAgo(0.7),
    violationType: "bus_stop_junction",
    note: "Parked right at the bus stop, buses can't pull in",
    lat: 12.9831,
    lng: 77.6089,
    accuracyM: 12,
    photoUrl: streetView(12.9831, 77.6089, 180),
    snappedRoadId: "commercial-street",
    snappedRoadName: "Commercial Street",
    snappedZone: "Central",
    snappedDistanceM: 22,
    reporterMasked: "+91 ●●●●● ●819",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.87,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-3",
    createdAt: hoursAgo(1.1),
    violationType: "wrong_parking",
    note: null,
    lat: 12.9720,
    lng: 77.6415,
    accuracyM: 15,
    photoUrl: streetView(12.9720, 77.6415, 270),
    snappedRoadId: "indiranagar-100ft",
    snappedRoadName: "Indiranagar 100 Feet Road",
    snappedZone: "East",
    snappedDistanceM: 31,
    reporterMasked: "+91 ●●●●● ●507",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.84,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-4",
    createdAt: hoursAgo(1.5),
    violationType: "footpath",
    note: "Vehicle on footpath, pedestrians walking on road",
    lat: 12.9752,
    lng: 77.6049,
    accuracyM: 10,
    photoUrl: streetView(12.9752, 77.6049, 0),
    snappedRoadId: "church-street",
    snappedRoadName: "Church Street",
    snappedZone: "Central",
    snappedDistanceM: 14,
    reporterMasked: "+91 ●●●●● ●123",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.79,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-5",
    createdAt: hoursAgo(2.0),
    violationType: "wrong_parking",
    note: null,
    lat: 12.9354,
    lng: 77.6228,
    accuracyM: 20,
    photoUrl: streetView(12.9354, 77.6228, 90),
    snappedRoadId: "koramangala-80ft",
    snappedRoadName: "Koramangala 80 Feet Road",
    snappedZone: "South East",
    snappedDistanceM: 26,
    reporterMasked: "+91 ●●●●● ●664",
    status: "new",
    dispatchId: null,
    aiVerdict: "skipped",
    aiConfidence: null,
    aiLabel: null,
  },
  {
    id: "demo-6",
    createdAt: hoursAgo(2.4),
    violationType: "driveway",
    note: "Car blocking apartment gate, residents can't exit",
    lat: 12.9785,
    lng: 77.6383,
    accuracyM: 9,
    photoUrl: streetView(12.9785, 77.6383, 90),
    snappedRoadId: "cmh-road",
    snappedRoadName: "CMH Road",
    snappedZone: "East",
    snappedDistanceM: 19,
    reporterMasked: "+91 ●●●●● ●991",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.93,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-7",
    createdAt: hoursAgo(3.2),
    violationType: "double_parking",
    note: null,
    lat: 12.9721,
    lng: 77.6071,
    accuracyM: 11,
    photoUrl: streetView(12.9721, 77.6071, 270),
    snappedRoadId: "brigade-road",
    snappedRoadName: "Brigade Road",
    snappedZone: "Central",
    snappedDistanceM: 24,
    reporterMasked: "+91 ●●●●● ●448",
    status: "reviewed",
    dispatchId: "d-demo-7",
    aiVerdict: "violation",
    aiConfidence: 0.88,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-8",
    createdAt: hoursAgo(4.1),
    violationType: "wrong_parking",
    note: "Near school gate during pickup time, very dangerous",
    lat: 12.9252,
    lng: 77.5832,
    accuracyM: 16,
    photoUrl: streetView(12.9252, 77.5832, 180),
    snappedRoadId: "jayanagar-4th",
    snappedRoadName: "Jayanagar 4th Block",
    snappedZone: "South",
    snappedDistanceM: 28,
    reporterMasked: "+91 ●●●●● ●730",
    status: "reviewed",
    dispatchId: "d-demo-8",
    aiVerdict: "violation",
    aiConfidence: 0.82,
    aiLabel: "illegal_parking",
  },
];
