import type { CitizenReport } from "@/lib/types";

/** Demo citizen reports seeded at real Bengaluru road coordinates.
 *  Shown on the Reports map when no live Supabase data exists yet. */

function hoursAgo(h: number): string {
  return new Date(Date.now() - h * 60 * 60 * 1000).toISOString();
}

function photo(label: string, bg = "111827", fg = "4ade80"): string {
  return `https://placehold.co/800x600/${bg}/${fg}?text=${encodeURIComponent(label)}`;
}

export const DEMO_REPORTS: CitizenReport[] = [
  {
    id: "demo-1",
    createdAt: hoursAgo(0.3),
    violationType: "double_parking",
    note: "Blocking entire lane, cars stuck for 10+ minutes",
    lat: 12.9758,
    lng: 77.6096,
    accuracyM: 8,
    photoUrl: photo("Double Parking\nMG Road", "0f172a", "f97316"),
    snappedRoadId: "mg-road-metro",
    snappedRoadName: "MG Road",
    snappedZone: "Central",
    snappedDistanceM: 18,
    reporterMasked: "+91 ●●●●● ●342",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.91,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-2",
    createdAt: hoursAgo(0.7),
    violationType: "bus_stop_junction",
    note: "Parked right at the bus stop, buses can't pull in",
    lat: 12.9831,
    lng: 77.6089,
    accuracyM: 12,
    photoUrl: photo("Bus Stop Blocked\nCommercial Street", "0f172a", "ef4444"),
    snappedRoadId: "commercial-street",
    snappedRoadName: "Commercial Street",
    snappedZone: "Central",
    snappedDistanceM: 22,
    reporterMasked: "+91 ●●●●● ●819",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.87,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-3",
    createdAt: hoursAgo(1.1),
    violationType: "wrong_parking",
    note: null,
    lat: 12.9720,
    lng: 77.6415,
    accuracyM: 15,
    photoUrl: photo("Wrong Parking\nIndiranagar 100ft Road", "0f172a", "facc15"),
    snappedRoadId: "indiranagar-100ft",
    snappedRoadName: "Indiranagar 100 Feet Road",
    snappedZone: "East",
    snappedDistanceM: 31,
    reporterMasked: "+91 ●●●●● ●507",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.84,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-4",
    createdAt: hoursAgo(1.5),
    violationType: "footpath",
    note: "Vehicle on footpath, pedestrians walking on road",
    lat: 12.9752,
    lng: 77.6049,
    accuracyM: 10,
    photoUrl: photo("Footpath Blocked\nChurch Street", "0f172a", "a78bfa"),
    snappedRoadId: "church-street",
    snappedRoadName: "Church Street",
    snappedZone: "Central",
    snappedDistanceM: 14,
    reporterMasked: "+91 ●●●●● ●123",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.79,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-5",
    createdAt: hoursAgo(2.0),
    violationType: "wrong_parking",
    note: null,
    lat: 12.9354,
    lng: 77.6228,
    accuracyM: 20,
    photoUrl: photo("Wrong Parking\nKoramangala 80ft Road", "0f172a", "34d399"),
    snappedRoadId: "koramangala-80ft",
    snappedRoadName: "Koramangala 80 Feet Road",
    snappedZone: "South East",
    snappedDistanceM: 26,
    reporterMasked: "+91 ●●●●● ●664",
    status: "new",
    dispatchId: null,
    aiVerdict: "skipped",
    aiConfidence: null,
    aiLabel: null,
  },
  {
    id: "demo-6",
    createdAt: hoursAgo(2.4),
    violationType: "driveway",
    note: "Car blocking apartment gate, residents can't exit",
    lat: 12.9785,
    lng: 77.6383,
    accuracyM: 9,
    photoUrl: photo("Driveway Blocked\nCMH Road", "0f172a", "38bdf8"),
    snappedRoadId: "cmh-road",
    snappedRoadName: "CMH Road",
    snappedZone: "East",
    snappedDistanceM: 19,
    reporterMasked: "+91 ●●●●● ●991",
    status: "new",
    dispatchId: null,
    aiVerdict: "violation",
    aiConfidence: 0.93,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-7",
    createdAt: hoursAgo(3.2),
    violationType: "double_parking",
    note: null,
    lat: 12.9721,
    lng: 77.6071,
    accuracyM: 11,
    photoUrl: photo("Double Parking\nBrigade Road", "0f172a", "f97316"),
    snappedRoadId: "brigade-road",
    snappedRoadName: "Brigade Road",
    snappedZone: "Central",
    snappedDistanceM: 24,
    reporterMasked: "+91 ●●●●● ●448",
    status: "reviewed",
    dispatchId: "d-demo-7",
    aiVerdict: "violation",
    aiConfidence: 0.88,
    aiLabel: "illegal_parking",
  },
  {
    id: "demo-8",
    createdAt: hoursAgo(4.1),
    violationType: "wrong_parking",
    note: "Near school gate during pickup time, very dangerous",
    lat: 12.9252,
    lng: 77.5832,
    accuracyM: 16,
    photoUrl: photo("Wrong Parking\nJayanagar 4th Block", "0f172a", "4ade80"),
    snappedRoadId: "jayanagar-4th",
    snappedRoadName: "Jayanagar 4th Block",
    snappedZone: "South",
    snappedDistanceM: 28,
    reporterMasked: "+91 ●●●●● ●730",
    status: "reviewed",
    dispatchId: "d-demo-8",
    aiVerdict: "violation",
    aiConfidence: 0.82,
    aiLabel: "illegal_parking",
  },
];
