import type { Road } from "@/lib/types";

/** Seed road + the parking curve the simulation replays for it.
 *  `peakParked` illegally parked vehicles, peaking at `peakMin` minutes after sim
 *  start, with Gaussian spread `spread`. The contrast that makes the whole pitch:
 *  narrow lanes have tiny `widthM` but huge `sensitivityKmphPerVehicle`. */
export interface SeedRoad extends Road {
  peakParked: number;
  peakMin: number;
  spread: number;
}

// Sim starts Friday 17:30. Evening peak lands ~18:10–18:20 (minutes 40–50).
export const SEED_ROADS: SeedRoad[] = [
  {
    id: "mg-road-metro",
    name: "MG Road",
    zone: "Central",
    nearLandmark: "MG Road Metro",
    roadClass: "sub_arterial",
    lanes: 4,
    widthM: 14,
    sensitivityKmphPerVehicle: 1.8,
    freeFlowKmph: 38,
    baseVolume: 2600,
    chronic: true,
    point: [77.6094, 12.9756],
    peakParked: 12,
    peakMin: 40,
    spread: 15,
  },
  {
    id: "indiranagar-100ft",
    name: "Indiranagar 100 Feet Road",
    zone: "East",
    nearLandmark: "CMH Road junction",
    roadClass: "sub_arterial",
    lanes: 4,
    widthM: 22,
    sensitivityKmphPerVehicle: 1.5,
    freeFlowKmph: 40,
    baseVolume: 2400,
    chronic: true,
    point: [77.6412, 12.9719],
    peakParked: 11,
    peakMin: 46,
    spread: 17,
  },
  {
    id: "commercial-street",
    name: "Commercial Street",
    zone: "Central",
    nearLandmark: "Shivajinagar",
    roadClass: "local",
    lanes: 1,
    widthM: 7,
    sensitivityKmphPerVehicle: 3.4,
    freeFlowKmph: 18,
    baseVolume: 1100,
    chronic: true,
    point: [77.6092, 12.9829],
    peakParked: 11,
    peakMin: 38,
    spread: 19,
  },
  {
    id: "church-street",
    name: "Church Street",
    zone: "Central",
    nearLandmark: "Brigade Road",
    roadClass: "local",
    lanes: 2,
    widthM: 9,
    sensitivityKmphPerVehicle: 3.0,
    freeFlowKmph: 22,
    baseVolume: 1250,
    chronic: true,
    point: [77.6046, 12.9750],
    peakParked: 9,
    peakMin: 42,
    spread: 18,
  },
  {
    id: "brigade-road",
    name: "Brigade Road",
    zone: "Central",
    nearLandmark: "Brigade Road",
    roadClass: "collector",
    lanes: 2,
    widthM: 11,
    sensitivityKmphPerVehicle: 2.4,
    freeFlowKmph: 28,
    baseVolume: 1800,
    chronic: true,
    point: [77.6068, 12.9719],
    peakParked: 8,
    peakMin: 44,
    spread: 18,
  },
  {
    id: "jayanagar-4th",
    name: "Jayanagar 4th Block",
    zone: "South",
    nearLandmark: "4th Block Market",
    roadClass: "collector",
    lanes: 2,
    widthM: 12,
    sensitivityKmphPerVehicle: 2.1,
    freeFlowKmph: 28,
    baseVolume: 1700,
    chronic: true,
    point: [77.5830, 12.9250],
    peakParked: 9,
    peakMin: 50,
    spread: 20,
  },
  {
    id: "cmh-road",
    name: "CMH Road",
    zone: "East",
    nearLandmark: "Indiranagar",
    roadClass: "collector",
    lanes: 2,
    widthM: 12,
    sensitivityKmphPerVehicle: 2.0,
    freeFlowKmph: 26,
    baseVolume: 1500,
    chronic: true,
    point: [77.6381, 12.9783],
    peakParked: 8,
    peakMin: 40,
    spread: 18,
  },
  {
    id: "koramangala-80ft",
    name: "Koramangala 80 Feet Road",
    zone: "South East",
    nearLandmark: "Sony World Junction",
    roadClass: "sub_arterial",
    lanes: 4,
    widthM: 24,
    sensitivityKmphPerVehicle: 1.3,
    freeFlowKmph: 42,
    baseVolume: 2300,
    chronic: false,
    point: [77.6230, 12.9352],
    peakParked: 13,
    peakMin: 48,
    spread: 20,
  },
  {
    id: "residency-road",
    name: "Residency Road",
    zone: "Central",
    nearLandmark: "Richmond Circle",
    roadClass: "sub_arterial",
    lanes: 4,
    widthM: 18,
    sensitivityKmphPerVehicle: 1.6,
    freeFlowKmph: 34,
    baseVolume: 2200,
    chronic: false,
    point: [77.6030, 12.9690],
    peakParked: 9,
    peakMin: 46,
    spread: 18,
  },
  {
    id: "orr-marathahalli",
    name: "Outer Ring Road",
    zone: "East",
    nearLandmark: "Marathahalli",
    roadClass: "arterial",
    lanes: 8,
    widthM: 42,
    sensitivityKmphPerVehicle: 0.3,
    freeFlowKmph: 55,
    baseVolume: 4200,
    chronic: false,
    point: [77.6970, 12.9560],
    peakParked: 20,
    peakMin: 42,
    spread: 22,
  },
  {
    id: "whitefield-main",
    name: "Whitefield Main Road",
    zone: "East",
    nearLandmark: "Hope Farm",
    roadClass: "arterial",
    lanes: 6,
    widthM: 34,
    sensitivityKmphPerVehicle: 0.6,
    freeFlowKmph: 48,
    baseVolume: 3200,
    chronic: false,
    point: [77.7500, 12.9698],
    peakParked: 14,
    peakMin: 44,
    spread: 22,
  },
  {
    id: "sarjapur-road",
    name: "Sarjapur Road",
    zone: "South East",
    nearLandmark: "Iblur",
    roadClass: "arterial",
    lanes: 6,
    widthM: 30,
    sensitivityKmphPerVehicle: 0.5,
    freeFlowKmph: 50,
    baseVolume: 3000,
    chronic: false,
    point: [77.6680, 12.9180],
    peakParked: 12,
    peakMin: 46,
    spread: 22,
  },
];

export const ROADS: Road[] = SEED_ROADS.map(({ peakParked, peakMin, spread, ...road }) => {
  void peakParked;
  void peakMin;
  void spread;
  return road;
});

export const ROAD_BY_ID: Record<string, SeedRoad> = Object.fromEntries(
  SEED_ROADS.map((r) => [r.id, r]),
);

export const ZONES = ["Central", "East", "South", "South East"] as const;
